apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-main-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-main-app
  template:
    metadata:
      labels:
        app: dwk-main-app
    spec:
      containers:
      - name: dwk-main-app
        image: smuliii/dwk-main-app:latest
