apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # namespace: dwk-main
  name: dwk-volume-claim
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
