apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: todos-project
  name: todos-db-set
spec:
  selector:
    matchLabels:
      app: todos-db
  serviceName: todos-db
  replicas: 1
  template:
    metadata:
      labels:
        app: todos-db
    spec:
      containers:
        - name: todos-db
          image: postgres:13.4
          envFrom:
            - secretRef:
                name: todos-db-secret
          ports:
            - containerPort: 5432
              name: db
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
  volumeClaimTemplates:
    - metadata:
        namespace: todos-project
        name: todos-db-data-claim
      spec:
        storageClassName: manual
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: todos-project
  name: todos-db-data
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /tmp/kube-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0
---
apiVersion: v1
kind: Service
metadata:
  namespace: todos-project
  name: todos-db
spec:
  selector:
    app: todos-db
  clusterIP: None
  ports:
    - port: 5432
---
apiVersion: v1
kind: Secret
metadata:
  namespace: todos-project
  name: todos-db-secret
type: Opaque
data:
  # POSTGRES_DB: todos-project
  POSTGRES_DB: dG9kb3MtcHJvamVjdA==
  # POSTGRES_USER: postgres
  POSTGRES_USER: cG9zdGdyZXM=
  # POSTGRES_PASSWORD: postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=
