apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todos-project
  name: dwk-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
