apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: dwk-main
  name: dwk-ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-ping-pong-app
  template:
    metadata:
      labels:
        app: dwk-ping-pong-app
    spec:
      # volumes:
      #   - name: dwk-volume
      #     persistentVolumeClaim:
      #       claimName: dwk-volume-claim
      containers:
        - name: dwk-ping-pong-app
          image: smuliii/dwk-ping-pong-app@sha256:0db3b5af6d261003e630bb9878e75ba197494b2e4a277c62154f4eefe1e2e67f
          # volumeMounts:
          #   - name: dwk-volume
          #     mountPath: /app/files
          readinessProbe:
            httpGet:
              path: /pingpong
              port: 3002
          livenessProbe:
            httpGet:
              path: /pingpong
              port: 3002
