apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-ping-pong-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-ping-pong-app
  template:
    metadata:
      labels:
        app: dwk-ping-pong-app
    spec:
      volumes:
        - name: dwk-volume
          persistentVolumeClaim:
            claimName: dwk-volume-claim
      containers:
        - name: dwk-ping-pong-app
          image: smuliii/dwk-ping-pong-app@sha256:f33ce4e72351037e4668680cdc99320b86bd5dfa7a6afd83878f60a50bb51ce2
          volumeMounts:
            - name: dwk-volume
              mountPath: /app/files
