apiVersion: v1
kind: Service
metadata:
  namespace: dwk-main
  name: dwk-ping-pong-app-svc
spec:
  type: ClusterIP
  selector:
    app: dwk-ping-pong-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3002
