apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    initialDelay: 10s
    interval: 60s
    count: 10
    successCondition: result[0] < 0.1
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-stack-prometheus-0.prometheus:9090
        query: |
          sum(rate(container_cpu_usage_seconds_total{namespace="dwk-project-app"}[1m]))