apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dwk-project-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dwk-project-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
