apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-main
  name: dwk-main-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-main-app
  template:
    metadata:
      labels:
        app: dwk-main-app
    spec:
      volumes:
        - name: dwk-volume
          persistentVolumeClaim:
            claimName: dwk-volume-claim
      containers:
        - name: dwk-main-app-generator
          image: smuliii/dwk-main-app-generator@sha256:b1f97188bf5261985d003d3276935c11194f3396554a9e959e1f66d610789004
          volumeMounts:
            - name: dwk-volume
              mountPath: /app/files
        - name: dwk-main-app-reader
          image: smuliii/dwk-main-app-reader@sha256:6ef9347c94ce44d62905b42250b32624304e4aa727202543f63d46a6b153b7dc
          env:
            - name: PINGPONG_URL
              value: http://dwk-ping-pong-app-svc:2345
          envFrom:
            - configMapRef:
                name: dwk-main-app-conf
          volumeMounts:
            - name: dwk-volume
              mountPath: /app/files
