apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dwk-project-app
resources:
  - manifests/namespace.yml
  - manifests/cron.yml
  - manifests/db.yml
  - manifests/deployment.yml
  - manifests/ingress.yml
  - manifests/persistentvolume.yml
  - manifests/persistentvolumeclaim.yml
  - manifests/service.yml
  # - manifests/horizontalpodautoscaler.yml
images:
  - name: dwk-project-app-frontend-image
    newName: smuliii/dwk-project-app-frontend
    digest: sha256:83e9842a9f5c705c7156b776368fc2bf011cef7bc39ad3d0ea35f5a7229b7413
  - name: dwk-project-app-backend-image
    newName: smuliii/dwk-project-app-backend
    digest: sha256:6ed298b5c83be4b16f2d006f9e62d69d8fbf11e51bfa95e30ffd2fa6a3bb58a0
configMapGenerator:
  - name: dwk-project-app-config
    envs:
      - config/configmap.env
secretGenerator:
  - name: dwk-project-app-secrets
    envs:
      - config/secrets.env
