apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dwk-project-app
# configurations:
  # - manifests/rollout-transform.yaml
  # - manifests/analysistemplate.yml
  # - manifests/rollout.yml
resources:
- manifests/namespace.yml
- manifests/cron.yml
- manifests/db.yml
- manifests/deployment.yml
- manifests/broadcaster.yml
- manifests/ingress.yml
- manifests/persistentvolume.yml
- manifests/persistentvolumeclaim.yml
- manifests/service.yml
  # - manifests/horizontalpodautoscaler.yml
images:
- name: dwk-project-app-backend-image
  newName: smuliii/dwk-project-app-backend
  newTag: f745dbe78e27283a71c4946bd929651b6ab27afe
- name: dwk-project-app-broadcaster-image
  newName: smuliii/dwk-project-app-broadcaster
  newTag: f745dbe78e27283a71c4946bd929651b6ab27afe
- name: dwk-project-app-frontend-image
  newName: smuliii/dwk-project-app-frontend
  newTag: f745dbe78e27283a71c4946bd929651b6ab27afe
configMapGenerator:
- envs:
  - config/configmap.env
  name: dwk-project-app-config
secretGenerator:
- envs:
  - config/secrets.env
  name: dwk-project-app-secrets
