name: GKE Pipeline

on:
  push:
    branches:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-a
  DEPLOYMENT_NAME: dwk-project-app
  BACKEND_APP_IMAGE: dwk-project-app-backend
  FRONTEND_APP_IMAGE: dwk-project-app-frontend

jobs:
  gke_deployment:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: part3/project-app
    steps:
      - uses: actions/checkout@v2
      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud container clusters get-credentials $GKE_CLUSTER --zone=$GKE_ZONE
      - run: gcloud --quiet auth configure-docker

      - run: echo "BACKEND_APP_IMAGE_WITH_TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/$BACKEND_APP_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
      - run: echo "FRONTEND_APP_IMAGE_WITH_TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/$FRONTEND_APP_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build backend app
        working-directory: part3/project-app/backend
        run: docker build . -t $BACKEND_APP_IMAGE_WITH_TAG
      - name: Publish backend app
        run: docker push $BACKEND_APP_IMAGE_WITH_TAG

      - name: Build backend app
        working-directory: part3/project-app/frontend
        run: docker build . -t $FRONTEND_APP_IMAGE_WITH_TAG
      - name: Publish backend app
        run: docker push $FRONTEND_APP_IMAGE_WITH_TAG

      - name: Set up Kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

      - if: startsWith(github.ref, 'refs/heads/main')
        run: echo "GKE_NAMESPACE=default" >> $GITHUB_ENV
      - if: "!startsWith(github.ref, 'refs/heads/main')"
        run: echo "GKE_NAMESPACE=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Deploy
        run: |-
          kubectl create namespace $GKE_NAMESPACE || true
          kubectl config set-context --current --namespace=$GKE_NAMESPACE
          ./kustomize edit set namespace $GKE_NAMESPACE
          ./kustomize edit set image BACKEND_APP_IMAGE=$BACKEND_APP_IMAGE_WITH_TAG
          ./kustomize edit set image FRONTEND_APP_IMAGE=$FRONTEND_APP_IMAGE_WITH_TAG
          kubectl apply -k .
          kubectl rollout status deployment $DEPLOYMENT_NAME
