name: GitOps Flux Pipeline

on:
  push:
    branches:
    paths:
      - 'part4/project-app/**'
  workflow_dispatch:

env:
  FRONTEND_APP_IMAGE: smuliii/dwk-project-app-frontend
  BACKEND_APP_IMAGE: smuliii/dwk-project-app-backend
  BROADCASTER_APP_IMAGE: smuliii/dwk-project-app-broadcaster

jobs:
  gitops_images_update:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: part4/project-app
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo "FRONTEND_APP_IMAGE_WITH_TAG=$FRONTEND_APP_IMAGE:$GITHUB_SHA" >> $GITHUB_ENV
      - run: echo "BACKEND_APP_IMAGE_WITH_TAG=$BACKEND_APP_IMAGE:$GITHUB_SHA" >> $GITHUB_ENV
      - run: echo "BROADCASTER_APP_IMAGE_WITH_TAG=$BROADCASTER_APP_IMAGE:$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and push frontend app
        working-directory: part4/project-app/frontend
        run: docker build . -t $FRONTEND_APP_IMAGE_WITH_TAG && docker push $FRONTEND_APP_IMAGE_WITH_TAG

      - name: Build and push backend app
        working-directory: part4/project-app/backend
        run: docker build . -t $BACKEND_APP_IMAGE_WITH_TAG && docker push $BACKEND_APP_IMAGE_WITH_TAG

      - name: Build and push broadcaster app
        working-directory: part4/project-app/broadcaster
        run: docker build . -t $BROADCASTER_APP_IMAGE_WITH_TAG && docker push $BROADCASTER_APP_IMAGE_WITH_TAG

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Update kustomize.yaml
        run: |-
          kustomize edit set image dwk-project-app-frontend-image=$FRONTEND_APP_IMAGE_WITH_TAG
          kustomize edit set image dwk-project-app-backend-image=$BACKEND_APP_IMAGE_WITH_TAG
          kustomize edit set image dwk-project-app-broadcaster-image=$BROADCASTER_APP_IMAGE_WITH_TAG

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          message: Build new gitops project-app images ($GITHUB_SHA)
